### PR TITLE
Chore/use-playwright

### PR DESCRIPTION
**Pull request by kepta**

### CODE REVIEW

**Comment by lucywang000** [comment]
I'm curious to know what's the motivation to switch to playwright from puppeteer for integration tests? :)

**Comment by kepta** [comment]
> I'm curious to know what's the motivation to switch to playwright from puppeteer for integration tests? :) 

Thanks for asking! I have had some good success using playwright in https://github.com/bangle-io/bangle-io/ and I think some of the reasons are:
- It has a first party tooling for running tests. In Puppeteer I was relying on `jest-puppeteer` which was a bit buggy. 
- More importantly Playwright has a lot of features baked in to reduce the flakiness like [trace-viewer](https://playwright.dev/docs/trace-viewer), [locators](https://playwright.dev/docs/locators) , better concurrency and sharding.

**Comment by lucywang000** [comment]
For what it's worth, you may also be interested in [Cypress](https://www.cypress.io/) , which also has the two advantages you mentioned above.

**Comment by kepta** [comment]
> or what it's worth, you may also be interested in [Cypress](https://www.cypress.io/) , which also has the two advantages you mentioned above.

Thanks for the suggestion, I did consider `Cypress` but the fact that it runs in the same thread and is not open sourced made go with playwright. But I do see its advantages w.r.t their SaaS offering.

**Comment by lucywang000** [comment]
emm .. I do think cypress is [open sourced](https://github.com/cypress-io/cypress). The commercial part is their "dashboard" service that could store historic test run results/videos/screenshots etc, and also provides some "distributed/parallel runner" feature, which are all totally optional.

**Pull request merged**
