### PR TITLE
Fixed input rule for ordered list

### PR DESCRIPTION
**Pull request by cgorrieri**

### CODE REVIEW

**Comment by cgorrieri** [comment]
I see it is working on your page https://bangle.dev/ but for some reason on my setup it is not working unless I put `\s` as the whitespace.

**Comment by kepta** [comment]
> I see it is working on your page https://bangle.dev/ but for some reason on my setup it is not working unless I put \s as the whitespace.

Hey thanks for sending this PR, can you provide more details on your setup ? I am a bit hesitant in using `\s` as it also includes `new line` and `tab`.

**Comment by cgorrieri** [comment]
My setup is not very different. I use the latest version of bangle.dev with some plugins that I wrote that don't have any input rules.
I can see that you are using `\s` for the last white space for headers, bullet lists, todo lists, so why would it be a problem here?

**Comment by kepta** [comment]
That’s a valid point. I forgot about that, recollecting my thoughts I think it is not possible to get new line so \s should be fine.

**Comment by kepta** [comment]
Thanks for helping make bangle.dev better.

**Comment by cgorrieri** [comment]
Thank you @kepta I plan on contributing more as I really like what you are doing here,

**Pull request merged**
